## Numpy array and basics  - 

In [187]:
import numpy as np

### Creating array from list


In [188]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : - ",arr_1d)

1D array : -  [1 2 3 4 5]


In [189]:
arr_2d = np.array([[1,2,3],[4,5,7]])
print(f"2D array - {arr_2d}")

2D array - [[1 2 3]
 [4 5 7]]


List vs Numpy Array

In [190]:
py_list = [1,2,3]
print(f"Python list multiplication {py_list * 2}") #List is duplicated

Python list multiplication [1, 2, 3, 1, 2, 3]


In [191]:
np_array = np.array([1,2,4])
print(f"Numpy multiplication {np_array * 2}")  #Values are multiplied -- Element wise multiplication

import  time
start  = time.time()
py_list = [i*2 for i in range(1000000)]
print(f"\n List operation time : {time.time()-start}")


start = time.time()
np_array = np.arange(1000000) * 2
print(f"\n Numpy operation time : {time.time()-start}")

Numpy multiplication [2 4 8]

 List operation time : 0.03116321563720703

 Numpy operation time : 0.010535955429077148


Creating array from scartch

In [192]:
zeros = np.zeros((3,4))
print(f"zeros array 3 Rows,4 Cols\n {zeros}")

zeros array 3 Rows,4 Cols
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [193]:
ones = np.ones((2,3))
print(f"One's array 2 Rows,4Cols\n {ones}")

One's array 2 Rows,4Cols
 [[1. 1. 1.]
 [1. 1. 1.]]


In [194]:
full = np.full((2,2),7)
print(f"Full array : - \n {full}")

Full array : - 
 [[7 7]
 [7 7]]


In [195]:
random = np.random.random((2,3))
print(f"Random array - \n{random}")

Random array - 
[[0.79221767 0.52988847 0.4947863 ]
 [0.98261936 0.51432433 0.77562828]]


In [196]:
sequence = np.arange(0,10,2)
print(f"Seq array - \n{sequence}")

Seq array - 
[0 2 4 6 8]


Vector , Matrix and Tensor


In [197]:
vector  = np.array([1,2,3])
matrix  = np.array([[1,2,3],
                    [4,5,6]])
print(f"Matrix- \n{matrix}")

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print(f"Tensor - \n{tensor}")  #Multi-dimensional array

Matrix- 
[[1 2 3]
 [4 5 6]]
Tensor - 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties


In [198]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Shape - {arr.shape}") #Gives rows and cols
print(f"Dimension  - {arr.ndim}")
print(f"Size  - {arr.size}") #Elements
print(f"DType  - {arr.dtype}") #Datatype


Shape - (2, 3)
Dimension  - 2
Size  - 6
DType  - int64
