## Numpy array and basics  - 

In [27]:
import numpy as np

### Creating array from list


In [28]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : - ",arr_1d)

1D array : -  [1 2 3 4 5]


In [29]:
arr_2d = np.array([[1,2,3],[4,5,7]])
print(f"2D array - {arr_2d}")

2D array - [[1 2 3]
 [4 5 7]]


List vs Numpy Array

In [30]:
py_list = [1,2,3]
print(f"Python list multiplication {py_list * 2}") #List is duplicated

Python list multiplication [1, 2, 3, 1, 2, 3]


In [31]:
np_array = np.array([1,2,4])
print(f"Numpy multiplication {np_array * 2}")  #Values are multiplied -- Element wise multiplication

import  time
start  = time.time()
py_list = [i*2 for i in range(1000000)]
print(f"\n List operation time : {time.time()-start}")


start = time.time()
np_array = np.arange(1000000) * 2
print(f"\n Numpy operation time : {time.time()-start}")

Numpy multiplication [2 4 8]

 List operation time : 0.031075000762939453

 Numpy operation time : 0.003968954086303711


Creating array from scartch

In [32]:
zeros = np.zeros((3,4))
print(f"zeros array 3 Rows,4 Cols\n {zeros}")

zeros array 3 Rows,4 Cols
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
ones = np.ones((2,3))
print(f"One's array 2 Rows,4Cols\n {ones}")

One's array 2 Rows,4Cols
 [[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
full = np.full((2,2),7)
print(f"Full array : - \n {full}")

Full array : - 
 [[7 7]
 [7 7]]


In [35]:
random = np.random.random((2,3))
print(f"Random array - \n{random}")

Random array - 
[[0.25974514 0.07308386 0.57754493]
 [0.01167928 0.82871146 0.40244487]]


In [36]:
sequence = np.arange(0,10,2)
print(f"Seq array - \n{sequence}")

Seq array - 
[0 2 4 6 8]


Vector , Matrix and Tensor


In [37]:
vector  = np.array([1,2,3])
matrix  = np.array([[1,2,3],
                    [4,5,6]])
print(f"Matrix- \n{matrix}")

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print(f"Tensor - \n{tensor}")  #Multi-dimensional array

Matrix- 
[[1 2 3]
 [4 5 6]]
Tensor - 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties


In [38]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Shape - {arr.shape}") #Gives rows and cols
print(f"Dimension  - {arr.ndim}")
print(f"Size  - {arr.size}") #Elements
print(f"DType  - {arr.dtype}") #Datatype


Shape - (2, 3)
Dimension  - 2
Size  - 6
DType  - int64


Array Reshaping

In [39]:
arr = np.arange(12)
print(f"Original Array - {arr}")

reshaped_arr = arr.reshape((3,4)) #convert into rows and columns
print(f"Reshaped Array - {reshaped_arr}")

flattened_arr = reshaped_arr.flatten()
print(f"Flattened array - {flattened_arr}")

#returns view instead of copy
raveled_arr = reshaped_arr.ravel()
print(f"Raveled arr - {raveled_arr}")


transpose_arr = reshaped_arr.T
print(f"Transposed_array - {transpose_arr}")

Original Array - [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array - [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array - [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled arr - [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed_array - [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
