Practice Numpy

In [168]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [169]:
arr2 = np.array(([1,2,3,4,5],[2,3,4,5,6])) #2D Array
print(arr2.shape)

(2, 5)


In [170]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [171]:
##identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Numpy vectorized operation

In [172]:
arr1 = np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

#Elementwise operation having same index
print(f"Addition {arr1+arr2}")

print(f"Subtraction  {arr1-arr2}")

print(f"Multiplication  {arr1*arr2}")

Addition [11 22 33 44 55]
Subtraction  [ -9 -18 -27 -36 -45]
Multiplication  [ 10  40  90 160 250]


Universal Fn


In [173]:
arr = np.array([2,3,4,5,6])
print(f"Sq root - {np.sqrt(arr)}")


print(f"Exponential - {np.exp(arr)}") #By default Euler's number - 2.71828

print(f"Sine  {np.sin(arr)}")

print(f"Natural log {np.log(arr)}")


Sq root - [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential - [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural log [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


Slicing and indexing


In [174]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(f"1st Element - {arr[0,0]}") #Row nd column

print(f"{arr[1:,2:]}") #2nd Row and 3rd col

print(f"{arr[0:2,2:]}")

print(f"{arr[1:,1:3]}")

1st Element - 1
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


Modify array elements

In [175]:
arr[0,0] = 100
print(f"After modifying - {arr}")

arr[1:] = 100
print(f"{arr}")

After modifying - [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


Statistical concepts  - Normalization



In [176]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(data)
print(f"Mean  - {mean}")

median = np.median(data)
print(f"Median - {median}")


std_dev = np.std(data)
print(f"Standard Deviation - {std_dev}")

variance = np.var(data)
print(f"Variance - {variance}")

Mean  - 5.5
Median - 5.5
Standard Deviation - 2.8722813232690143
Variance - 8.25


Logical Operations

In [177]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data > 5) & (data<8)]

array([6, 7])